create table task_model (has_reminder boolean not null, id integer generated by default as identity, day_field varchar(255), text_field varchar(255), primary key (id));
create table task_model (has_reminder boolean not null, id integer generated by default as identity, day_field varchar(255), text_field varchar(255), primary key (id));
create table task_model (has_reminder boolean not null, id integer generated by default as identity, day_field varchar(255), text_field varchar(255), primary key (id));
create table task_model (has_reminder boolean not null, id integer generated by default as identity, day_field varchar(255), text_field varchar(255), primary key (id));
